docs/intro.rst

the images will not work w/ Docker for Mac.  adding disclaimer to the docs intro.

adding disclaimer for docker 4 mac

---

docs/quickstart.rst
docs/tutorials/clustered-deployment-sasl.rst

@samjhecht @arrawatia @theduderog

Sasl doc updates

---

debian/kafka-rest/include/etc/confluent/docker/apply-mesos-overrides

Need proper setting of KAFKA_REST_HOST when in mesos environments (same logic 
as done with other images).

Fix issue with Mesos deployment

---

debian/kafka-connect-base/include/etc/confluent/docker/configure

@samjhecht @theduderog Can you please review this PR ?

Fix for #147.

---

debian/schema-registry/include/etc/confluent/docker/admin.properties.template
debian/schema-registry/include/etc/confluent/docker/configure
debian/schema-registry/include/etc/confluent/docker/ensure

Fix Issue 176
https://github.com/confluentinc/cp-docker-images/issues/176
@arrawatia : Please review, thanks

Fix issue https://github.com/confluentinc/cp-docker-images/issues/176

---

debian/kafka/include/etc/confluent/docker/ensure

replaced KAFKA_DATA_DIRS by KAFKA_LOG_DIRS to bug in ensure

---

debian/base/Dockerfile

Added jq and unzip utilities to base image.

---

docs/intro.rst
docs/quickstart.rst

Some simple cleanup of the documented details on our docker images and the commands to deploy them

Review and update intro and quickstart docs

---

Makefile
tests/test_kafka.py

@theduderog Can you please review this PR ?

Fix tests for 3.1.2

---

.gitignore
Makefile

@arrawatia @samjhecht @jonchiu 
With this PR, you can put any custom build overrides you want in a local.make file.

Allow overrides in a local makefile

---

Makefile

@arrawatia @samjhecht @jonchiu 
Check errors when pushing images

Check errors on upload

---

java/pom.xml
java/src/main/java/io/confluent/admin/utils/KafkaAdminClient.java

I am creating this and other PRs for review before merging apache/kafka#2406.

Adapt to KAFKA-4636 changes

---

Makefile
debian/schema-registry/include/etc/confluent/docker/ensure
java/src/main/java/io/confluent/admin/utils/cli/KafkaReadyCommand.java

- Apply changes from #182 and #193 
- Bump up the build no
- Better error message for null bootstrap brokers.

Fix SSL issue for SR and RP

---

java/src/main/java/io/confluent/admin/utils/KafkaAdminClient.java

This seems to work (passes the tests)

Update for change in Metadata::change()

---

examples/enterprise-kafka/docker-compose.yml
examples/enterprise-replicator/docker-compose.yml
examples/kafka-cluster-sasl/docker-compose.yml
examples/kafka-cluster-ssl/docker-compose.yml
examples/kafka-cluster/docker-compose.yml
examples/kafka-single-node/docker-compose.yml
examples/kafka-streams-examples/docker-compose.yml

we need to map moby as an extra host

---

debian/base/include/dub

fix typo enviornment -> environment in dub

---

docs/tutorials/automatic-data-balancing.rst

I tried the above steps. I saw enterprisekafka_kafka-1_1 in Up status which looks reasonable.

Update the correct status in the documentation

---

README.md

Fixed link in README.md to our docs page on contributing changes to repo.

MINOR: Fix README.md to have proper link to the details on contributing to the project

---

README.md
docs/quickstart.rst

@aayars should this change be made for all versions?

DOCS-49 Clarify Docker for Mac and Windows limitation

---

docs/quickstart.rst
examples/kafka-single-node/docker-compose.yml

https://confluentinc.atlassian.net/browse/DOCS-4

DOCS-4 - Make Docker Compose more prominent

---

docs/configuration.rst
docs/development.rst
docs/index.rst
docs/intro.rst
docs/operations/external-volumes.rst
docs/operations/logging.rst
docs/operations/monitoring.rst
docs/quickstart.rst
docs/security/security.rst
docs/tutorials/automatic-data-balancing.rst
docs/tutorials/clustered-deployment-sasl.rst
docs/tutorials/clustered-deployment-ssl.rst
docs/tutorials/clustered-deployment.rst
docs/tutorials/connect-avro-jdbc.rst
docs/tutorials/replicator.rst

Changed `Zookeeper` to `ZooKeeper`
Changed `CP` to `Confluent Platform`

Fix ZK typos

---

docs/quickstart.rst
docs/tutorials/connect-avro-jdbc.rst

https://confluentinc.atlassian.net/browse/DOCS-114

DOCS-114 - Missing info in cp-docker (customer)

---

docs/tutorials/connect-avro-jdbc.rst

Set topic replication factor for all Connect topics in quickstart.

---

docs/configuration.rst
docs/security.rst
docs/tutorials/kafka-streams-examples.rst

https://confluentinc.atlassian.net/browse/DOCS-262

DOCS-262 - Fix linking

---

docs/configuration.rst

https://confluentinc.atlassian.net/browse/DOCS-218

DOCS-218 - docker example for replicator is wrong

---

docs/quickstart.rst

https://confluentinc.atlassian.net/browse/DOCS-273

DOCS-273 - Missing line in Docker quick start

---

docs/configuration.rst
docs/development.rst
docs/operations/external-volumes.rst
docs/operations/index.rst
docs/operations/monitoring.rst
docs/quickstart.rst
docs/tutorials/automatic-data-balancing.rst
docs/tutorials/clustered-deployment-sasl.rst
docs/tutorials/clustered-deployment-ssl.rst
docs/tutorials/clustered-deployment.rst
docs/tutorials/connect-avro-jdbc.rst
docs/tutorials/kafka-streams-examples.rst
docs/tutorials/replicator.rst

https://confluentinc.atlassian.net/browse/DOCS-375
- main change here https://github.com/confluentinc/cp-docker-images/pull/453/files#diff-4b982e95cfb672e3f6ccd4f9dcb0ab71R23
- PR also adds ZooKeeper string replacement

DOCS-375 - Add statement about mapping local dir path

---

docs/configuration.rst
docs/development.rst
docs/quickstart.rst
docs/tutorials/connect-avro-jdbc.rst

Follow-on to https://github.com/confluentinc/cp-docker-images/pull/465

Port PR465 to 4.0.0

---

docs/configuration.rst

drop config notes that no longer apply

DOCS-285: update config notes to reflect reality

---

docs/quickstart.rst

Reverts overwriting of https://github.com/confluentinc/cp-docker-images/pull/458/files#diff-9d8a6f5b32d4a70a56734fd0eb50dd5bL277

Fix bad merge that overwrote 458

---

debian/base/Dockerfile

FIXES #489
From https://github.com/zulu-openjdk/zulu-openjdk/blob/master/debian/8u172-8.30.0.1/Dockerfile

Updated java 8 to latest available

---

docs/configuration.rst

This depends on:
1. https://github.com/confluentinc/ksql/pull/1322
2. https://github.com/confluentinc/ksql/pull/1347

Add documentation for the KSQL docker images

---

debian/enterprise-control-center/include/etc/confluent/docker/control-center.properties.template

fix ksql endpoint config name

---

README.md
debian/kafka-connect-base/include/etc/confluent/docker/log4j.properties.template
docs/configuration.rst
docs/quickstart.rst
docs/tutorials/connect-avro-jdbc.rst

Apache Kafka already suppresses these in a way we prefer
Resolves CC-2102 
https://confluentinc.atlassian.net/browse/CC-2102

CC-2102 CP Connect Docker images suppress Reflections warnings

---

debian/enterprise-control-center/include/etc/confluent/docker/control-center.properties.template

This should fix some of our env config mapping issues and avoid missing configs in the future.

more generic mapping of env variables to properties

---

docs/quickstart.rst

https://confluentinc.atlassian.net/browse/DOCS-493

DOCS-493 - Fix ports

---

docs/quickstart.rst

https://confluentinc.atlassian.net/browse/DOCS-493
- follow-on to https://github.com/confluentinc/cp-docker-images/pull/509

DOCS-493 - Fix port follow-on

---

docs/installation/recipes/single-node-client.rst

Stumbled onto this while following the documentation and thought I'd help out

Fix invalid step order in single-node-client recipe doc

---

docs/installation/config-reference.rst

Adapted from [confluentinc/cp-ksql-server](https://hub.docker.com/r/confluentinc/cp-ksql-server/) and [confluentinc/cp-ksql-cli](https://hub.docker.com/r/confluentinc/cp-ksql-cli/) on Docker Hub.

DOCS-498: Add KSQL settings

---

docs/quickstart.rst

Verified the port assignment on Ubuntu 18.04.

DOCS-610: Update containerized Kafka port assignment to 29092

---

docs/quickstart.rst

Manual fix for merge conflict.

DOCS-610: Update containerized Kafka port to 29092

---

docs/installation/recipes/clustered-deployment-sasl.rst
docs/installation/recipes/clustered-deployment-ssl.rst
docs/installation/recipes/clustered-deployment.rst
docs/installation/recipes/connect-avro-jdbc.rst
docs/installation/recipes/replicator.rst

https://confluentinc.atlassian.net/browse/DOCS-512

DOCS-512 - Change all references of new consumer to consumer

---

docs/configuration.rst
docs/development.rst
docs/includes/docker-machine.rst
docs/installation/config-reference.rst
docs/installation/recipes/automatic-data-balancing.rst
docs/installation/recipes/clustered-deployment-sasl.rst
docs/installation/recipes/clustered-deployment-ssl.rst
docs/installation/recipes/clustered-deployment.rst
docs/installation/recipes/connect-avro-jdbc.rst
docs/installation/recipes/includes/docker-tutorials.rst
docs/installation/recipes/replicator.rst
docs/installation/recipes/single-node-client.rst
docs/operations/external-volumes.rst
docs/operations/logging.rst
docs/operations/monitoring.rst

https://confluentinc.atlassian.net/browse/DOCS-635
- Staging server here http://staging-docs.confluent.io.s3-website-us-west-2.amazonaws.com/5.0.0/installation/docker/docs/installation/recipes/single-node-client.html

DOCS-635 - Fix code versioning (add codewithvars)

---

docs/tutorials/clustered-deployment.rst

https://confluentinc.atlassian.net/browse/DOCS-613

DOCS-613 - Fix typo

---

docs/development.rst
docs/tutorials/connect-avro-jdbc.rst

https://confluentinc.atlassian.net/browse/DOCS-561

DOCS-561 - Update mysql version in Connect tutorial

---

docs/configuration.rst
docs/development.rst
docs/includes/docker-machine.rst
docs/installation/config-reference.rst
docs/installation/recipes/automatic-data-balancing.rst
docs/installation/recipes/clustered-deployment-sasl.rst
docs/installation/recipes/clustered-deployment-ssl.rst
docs/installation/recipes/clustered-deployment.rst
docs/installation/recipes/connect-avro-jdbc.rst
docs/installation/recipes/includes/docker-tutorials.rst
docs/installation/recipes/replicator.rst
docs/installation/recipes/single-node-client.rst
docs/operations/external-volumes.rst
docs/operations/logging.rst
docs/operations/monitoring.rst

Retargets https://github.com/confluentinc/cp-docker-images/pull/541/commits/c0731c43d3d920faef9a19cf8ecede9d567da03e to `5.0.0-post`

DOCS-635 - Port version fixes to 5.0.0-post

---

docs/tutorials/connect-avro-jdbc.rst

DOCS-735 - Add explicit MySQL version

---

docs/configuration.rst

https://confluentinc.atlassian.net/browse/DOCS-759
- Added hyperlink to https://docs.confluent.io/current/installation/versions-interoperability.html#java

DOCS-759 - Clarify supported Java

---

debian/kafka-connect-base/include/etc/confluent/docker/log4j.properties.template

Signed-off-by: Arjun Satish <arjun@confluent.io>

MINOR: Fix default log levels rendering in connect-log4j.properties

---

README.md

Whilst retaining link to known issues

Tone-down the note about Mac/Windows

---

examples/cp-all-in-one/Dockerfile
examples/cp-all-in-one/docker-compose.yml

Related to https://github.com/confluentinc/kafka-connect-datagen/pull/16

Keep Dockerfile local instead of pulling from different context

---

docs/installation/index.rst

- Related https://github.com/confluentinc/docs/pull/1516

DOCS-822 - Add link to multi-node docs

---

examples/multi-datacenter/README.md
examples/multi-datacenter/docker-compose.yml
examples/multi-datacenter/pom.xml

Automation tooling takes care of bumping image tags in docker-compose.yml files, but this takes care of the multi datacenter example

DEVX-778: update multidatacenter to 5.2.0

---

examples/cp-all-in-one/docker-compose.yml

```bash
connect            | WARNING: Did not find directory for kafka-connect-datagen (did you remember to run: docker-compose up -d --build ?)
```

DEVX-840: log warning if no directory for kafka-connect-datagen

---

debian/kafka-connect-base/include/etc/confluent/docker/configure
examples/cp-all-in-one-cloud/docker-compose.yml
examples/cp-all-in-one/docker-compose.yml
examples/enterprise-replicator/docker-compose.yml
examples/multi-datacenter/docker-compose.yml
tests/test_kafka_connect.py

Remove mandatory internal converters configuration (deprecated AK2.0)

---

README.md

I am merging the deprecation notice that is on the master branch to the 5.3.3-post branch since that is our latest branch. I will also merge this to the 5.3.x branch so that any future post branches also get this notice. I have also moved the deprecation notice to the top of the page.

ST-3668: Update deprecation notice

---

debian/enterprise-control-center/Dockerfile
debian/enterprise-control-center/Dockerfile.rpm
debian/enterprise-kafka/Dockerfile
debian/enterprise-kafka/Dockerfile.rpm
debian/kafka-connect-base/Dockerfile
debian/kafka-mqtt/Dockerfile
debian/kafka-rest/Dockerfile
debian/kafka/Dockerfile
debian/kafka/Dockerfile.rpm
debian/schema-registry/Dockerfile
debian/zookeeper/Dockerfile
debian/zookeeper/Dockerfile.rpm

Part of hardening cp-docker images. Remove world write access on data directories.

feat: Disable world write access on data directories
