debian/kafka/include/etc/confluent/docker/log4j.properties.template

The root logger (line 2) already has "stdout", and thus it's inherited automatically by sub-loggers.  By specifying them in sub-loggers it results in twice the log messages.

Fix double log4j logging

---

docs/quickstart.rst

“docker-compose run” is not a required step and will return a syntax
error

docker-compose quick start doc fix

---

debian/base/Dockerfile
tests/test_enterprise_kafka.py
tests/test_kafka.py
tests/test_zookeeper.py

@samjhecht @theduderog Can you please review this PR ?
Changes:
- Change the deb URL to http://packages.confluent.io
- Fix all failing tests
We can build and upload docker images once we merge this PR.

Switch debian url to production

---

debian/zookeeper/include/etc/confluent/docker/configure

The warning message refers to KAFKA_OPTS but as you can see from the condition, the env var KAFKA_JMX_OPTS is what's pertinent.

JMX Warning message refers to wrong env var

---

debian/kafka-connect-base/include/etc/confluent/docker/ensure

Similar to #176 and #193 
This allows me to get past the kafka-ready step and use an http or https listener with an SSL Kafka cluster.
Fixes #189 
CC @amccague

kafka-ready for Kafka Connect fails when using SSL

---

debian/base/Dockerfile

When I built some of my docker images on top of the confluent, some programs were complaining that JAVA_HOME wasn't set. I think setting it at the base image level is best.

added JAVA_HOME

---

debian/zookeeper/include/etc/confluent/docker/zookeeper.properties.template
docs/development.rst
docs/security/security.rst

* Fix issue reported in #180 - make ZOOKEEPER_CLIENT_PORT default to 2181
* fix links to security tutorials per https://github.com/confluentinc/cp-docker-images/issues/190
* remove specific AMI from development docs `docker-machine create` example.  The one we included was no longer available and it's not necessary to specify it anyway.

Issue 180, 190 and docs improvements

---

Makefile
debian/base/Dockerfile

@arrawatia @samjhecht @jonchiu 
This keeps things the same by default but if you want to build with an unsigned deb repo, you can override like this:
`make CONFLUENT_DEB_REPO=http://foobar APT_ALLOW_UNAUTHENTICATED=true build-debian`

Update versions and allow builds from unsigned deb repos

---

debian/kafka-connect-base/include/etc/confluent/docker/log4j.properties.template

this mimic the behaviour at
https://github.com/confluentinc/cp-docker-images/blob/master/debian/kafka/include/etc/confluent/docker/log4j.properties.template#L25

Connect: Removed stdout from custom loggers so it doesn't output duplicate log

---

debian/kafka-connect-base/include/etc/confluent/docker/ensure

This is to backport changes to support SSL on kafka-ready for Kafka Connect in 3.1.x. @samjhecht or @arrawatia please take a look and if it's ok please publish updated images including this commit. Thanks!

kafka-ready for Kafka Connect fails when using SSL (#194)

---

debian/kafka-rest/include/etc/confluent/docker/ensure

This is a change similar to that for issue #176 but for Kafka Rest. Following a similar approach.
This allows me to get past the `kafka-ready` step and use an `http` or `https` listener with an SSL Kafka cluster.

kafka-rest: Fix for NullReferenceException in kafka-ready (SSL enabled)

---

debian/schema-registry/include/etc/confluent/docker/admin.properties.template
debian/schema-registry/include/etc/confluent/docker/configure
debian/schema-registry/include/etc/confluent/docker/ensure

- Apply changes from #178 
**How did i test ?**
Run a SSL enabled Kafka cluster : http://docs.confluent.io/3.2.0/cp-docker-images/docs/tutorials/clustered-deployment-ssl.html
**Run 2 node cluster** 
```
docker run -d --net=host --name=sr-ssl-1 -e SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=localhost:22181,localhost:32181,localhost:42181 -e SCHEMA_REGISTRY_HOST_NAME=localhost -e SCHEMA_REGISTRY_LISTENERS=http://localhost:8083 -e SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=SSL://localhost:29092 -e SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=SSL -e SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION=/etc/schema-registry/secrets/kafka.producer.keystore.jks -e SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD=confluent -e SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD=confluent -e …
```

Fix SR SSL issue

---

Makefile
debian/kafka-rest/include/etc/confluent/docker/admin.properties.template
debian/kafka-rest/include/etc/confluent/docker/configure
debian/kafka-rest/include/etc/confluent/docker/ensure
debian/schema-registry/include/etc/confluent/docker/ensure

- Add admin properties for kafka-ready.
- Increment build number.
**How did I test ?**
Run a SSL enabled Kafka cluster : http://docs.confluent.io/3.2.0/cp-docker-images/docs/tutorials/clustered-deployment-ssl.html
**Run Rest proxy**
```
docker run -d \
--net=host \
--name=kafka-rest \
-e KAFKA_REST_ZOOKEEPER_CONNECT=localhost:32181 \
-e KAFKA_REST_LISTENERS=https://localhost:8089 \
-e KAFKA_REST_SCHEMA_REGISTRY_URL=http://localhost:8082 \
-e KAFKA_REST_BOOTSTRAP_SERVERS="SSL://localhost:29092" \
-e KAFKA_REST_HOST_NAME=localhost \
-e KAFKA_REST_CLIENT_SECURITY_PROTOCOL=SSL \
-e KAFKA_REST_CLIENT_SSL_KEYSTORE_LOCATION="/etc/kafka-rest/secrets/kafka.producer.keystore.jks" \
-e KAFKA_REST_CLIENT_SSL_KEYSTORE_PASSWORD=confluent \
-e KAFKA_REST_CLIENT_SSL_TRUSTSTORE_PASSWORD=confluent \
-e …
```

Fix SSL issue for Rest Proxy

---

debian/enterprise-control-center/include/etc/confluent/docker/control-center.properties.template
tests/test_control_center.py

There does not appear to be a way to change the replication factor for the metrics topic. This is problematic if you plan to start a cluster with less than 3 brokers

We are missing the new metrics config

---

debian/enterprise-control-center/include/etc/confluent/docker/control-center.properties.template

This change patches an issue I ran into when starting the control-center container in the Docker Quickstart (http://docs.confluent.io/current/cp-docker-images/docs/quickstart.html). Please let me know if there's a better place to make this fix.
Log and stacktrace for the original issue:
```
#Ignoring Mesos override errors
. /etc/confluent/docker/apply-mesos-overrides || true
+ . /etc/confluent/docker/apply-mesos-overrides
#!/usr/bin/env bash
#
#
#
#
#
#
[ -n "${PORT:-}" ] && [ -n "${PORT_9021:-}" ] && [ "$PORT" = "${PORT_9021}" ] &&\
export PORT=9021 || true
++ '[' -n '' ']'
++ true
echo "===> ENV Variables ..."
+ echo '===> ENV Variables ...'
===> ENV Variables ...
env | sort
+ sort
+ env
APT_ALLOW_UNAUTHENTICATED=false
COMPONENT=control-center
CONFLUENT_DEB_VERSION=1 …
```

Pass environment variables to topic metrics settings

---

Makefile
docs/development.rst

`io.confluent.docker.build.number` may not be the greatest thing to use for this, but it is a label we only set in `cp-docker-images`

ST-394: we now tag our jenkins images with this label, so we get build errors  on jenkins. be more constrained

---

docs/tutorials/kafka-streams-examples.rst
examples/kafka-streams-examples/.env
examples/kafka-streams-examples/docker-compose.yml

As discussed offline, this not only fixes the startup problems introduced by https://github.com/confluentinc/cp-docker-images/commit/1971b7d9198832bc8b3494712d0c604de961bf3f, but also allows us to get rid off the Docker Machine Linux VM when running on Macs.
This PR should also go (with appropriate versioning-related changes etc. where needed) into:
- `v3.2.1`
- `3.2.x`
- `master`
**Note:** The documentation in `kafka-streams-examples.rst` in this PR, which is based against `3.2.1-post`, refers to checking out the branch `v3.2.1` to get the correct `docker-compose.yml` file:
```shell
$ git checkout v3.2.1
```
When we downmerge this PR to `3.2.x` and `master`, AFAICT we would need to update the branch reference accordingly, I think (not 100% sure, because the branch/naming convention is …

Kafka Streams docker demo: work without a VM on Macs

---

docs/tutorials/kafka-streams-examples.rst
examples/kafka-streams-examples/docker-compose.yml

This allows host-to-container communication (e.g. Mac laptop to running `kafka` container) via `localhost:9092`, in addition to inter-container communication to the Kafka broker via `kafka:29092`
**When merging into downstream branches**:  When merging into `v3.2.1` and further branches, this PR needs to add the following Docker setting to all containers:
```
extra_hosts:
- "moby:127.0.0.1"
```
I can provide this in a separate PR against `v3.2.1`, but I suppose we want to follow the normal merge-downwards approach...?

Allow accessing the Kafka broker via localhost:9092 from your Docker host machine

---

docs/tutorials/clustered-deployment-sasl.rst

The documentation for "Docker Compose: Setting Up a Three Node CP Cluster with SASL" was missing clear instructions for using docker-machine with docker-compose. It was also not clear how to build and run the kerberos image. I've attempted to clear up the confusion for these 2 points.

Update doc for running SASL cluster using docker-compose

---

debian/kafka-connect-base/include/etc/confluent/docker/run

This pull request (PR) corrects the whitespace on a set call to make command consistent with those around it.

Corrected whitespace to be consistent with surrounding lines

---

debian/kafka-rest/include/etc/confluent/docker/apply-mesos-overrides

Minor fix for DC/OS environments to avoid multiple REST proxy instances with the same REST_ID being deployed.

Use MESOS_TASK_ID to set "id" property in kafka-rest.properties.

---

docs/configuration.rst

super minor change: 
https://confluentinc.atlassian.net/browse/DOCS-138

DOCS-138: fix reference to control center docker image

---

docs/development.rst

I added this command earlier to dub today (confluentinc/confluent-docker-utils#2). Just wanted to make sure I updated the docs while I was thinking about it.

Add dub path-wait command to docs

---

debian/kafka/Dockerfile
debian/kafka/include/etc/confluent/docker/run

Adding flexibility to the Kafka Docker image to allow `ARG` overrides of the two required environment variables.
```bash
docker build -t kafka \
--build-arg KAFKA_ZOOKEEPER_CONNECT=localhost:2181 \
--build-arg KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://test:9092  .
```
Add `RUN echo $KAFKA_ADVERTISED_LISTENERS` in Dockerfile after proposed edits and build using example above. The console will display the passed-in value for that env param and you can omit it in the `-e ` args during runtime as it is already set.
This also solves a major issue with attempted Kubernetes deployments using this image, given the unique POD IP cannot be passed dynamically in the `ENV` parameters. By adding the ability to also declare these two required values (checked at startup by configure script), this image can …

Add optional ARG overrides of required ENV params during build time

---

docs/tutorials/kafka-streams-examples.rst

Removes page that only contains redirect link. This is now done automatically. 
Related PR: https://github.com/confluentinc/docs/pull/727

Remove empty tutorials page

---

debian/kafka/include/etc/confluent/docker/configure

The line `if [[ $KAFKA_SSL_CLIENT_AUTH == *"required"* ]] || [[ $KAFKA_SSL_CLIENT_AUTH == *"requested"* ]]` causes an unbound variable error if the variable `$KAFKA_SSL_CLIENT_AUTH` is unset. This should fix that.

MINOR: Fix unbound variable bug for KAFKA_SSL_CLIENT_AUTH

---

debian/kafka-connect/Dockerfile
docs/development.rst
tests/fixtures/debian/kafka-connect/distributed-single-node.yml
tests/test_kafka_connect.py

Also added test for the ActiveMQ connector. The Docker image includes JMS connector, ActiveMQ connector, and IBM MQ connector, but it’s very difficult to add messages to MQ (no command line utility) and so it’s going to be tough to write tests.

CC-1663: Added JMS connectors to Connect image

---

docs/quickstart.rst

Moved all networking to a user-defined network which comes with DNS resolution by default
If we confirm this also works on Docker for Windows, we can probably remove the remaining mentions of docker-machine as well.

Modify quickstart to work with Docker for Mac

---

examples/cp-all-in-one/docker-compose.yml
examples/enterprise-replicator/docker-compose.yml

This PR adds the `plugin.path` configuration in Connect examples. Also, it reduces the log verbosity in these containers by increasing the levels for `org.reflections` and other library packages to ERROR level.
Signed-off-by: Arjun Satish <arjun@confluent.io>

MINOR: Add env vars to set plugin path and log levels

---

docs/configuration.rst
docs/development.rst
docs/quickstart.rst
docs/tutorials/connect-avro-jdbc.rst

Fixes a few place where "it's" is mistakenly used instead of "its".

DOCS-405 - Correct usage of "its" vs "it's" in cp-docker-images

---

docs/tutorials/clustered-deployment-sasl.rst
docs/tutorials/clustered-deployment-ssl.rst
docs/tutorials/clustered-deployment.rst
docs/tutorials/connect-avro-jdbc.rst
docs/tutorials/replicator.rst
tests/test_control_center.py
tests/test_enterprise_replicator.py
tests/test_kafka.py

It's a no-op in recent versions and it will be
removed in Apache Kafka 2.0.0.

Remove redundant --new-consumer option

---

examples/cp-all-in-one/docker-compose.yml

In the single node cluster use open port as 9092 for kafka brokers which is the standard

Use standard port for kafka brokers : 9092

---

docs/installation/config-reference.rst

When I added the KSQL Server and CLI sections, I munged the `codewithvars` blocks – magic whitespace to the rescue!

DOCS-595: Fix munged code blocks

---

examples/kafka-cluster-ssl/docker-compose.yml
examples/kafka-cluster-ssl/secrets/host.consumer.ssl.config
examples/kafka-cluster-ssl/secrets/host.producer.ssl.config

The recent addition of a default value for the `ssl.endpoint.identification.algorithm` has caused things to break; overriding it with a blank value has helped for the most part.
`ssl.client.auth` is set to `requested` since things also break if it isn't. Not familiar with SSL, either in general or with Kafka, so I can't say much more than that. What's certain is that the example doesn't work without that line and it does work with it.

Fix kafka-cluster-ssl example

---

docs/operations/external-volumes.rst
docs/operations/logging.rst
docs/operations/monitoring.rst

Added `Docker` to topic titles to improve navigation and SEO in docs.confluent.io

DOCS-630 - Add Docker-specific titles

---

docs/configuration.rst
docs/development.rst

[JIRA](https://confluentinc.atlassian.net/browse/CC-2049)
This adds an example on how to use the `cp-kafka-connect[-base]` images and the `confluent-hub` client tool to create a Kafka Connect image with a custom set of connectors included.

CC-2049: Add documentation for creating custom Connect images via Confluent Hub

---

debian/enterprise-control-center/include/etc/confluent/docker/ensure

At the moment the timeout is 40 seconds, which may well not be long enough for the broker(s) to come up particularly on a machine running the full stack.

Increase timeout for Kafka brokers to be available

---

examples/kafka-single-node/docker-compose.yml

We need an example that shows people how to wire Kafka on Docker for both internal and external connections.

Add second listener and some text explaining its use

---

debian/kafka-connect-base/include/etc/confluent/docker/log4j.properties.template

Backport the fix from https://github.com/confluentinc/cp-docker-images/pull/623 to 3.2.x.
Signed-off-by: Arjun Satish <arjun@confluent.io>

MINOR: Fix default log levels rendering in connect-log4j.properties

---

examples/cp-all-in-one/README.md
examples/cp-all-in-one/docker-compose.yml

This updates cp-all-in-one  connect image to have the connector https://www.confluent.io/connector/kafka-connect-datagen/ (to be used by CP quickstart)

DEVX-318: build Docker image to include kafka-connect-datagen

---

debian/kafkacat/Dockerfile

Root CA certs are required to connect to ccloud.

cp-kafkacat: add ca-certificates

---

debian/kafka-connect-base/Dockerfile

[Jira](https://confluentinc.atlassian.net/browse/CC-5432)
We need to include the `confluent-security` package in our Docker image for Connect in order to support RBAC.

CC-5432: Add Confluent security plugins to Connect Docker image

---

Makefile
debian/enterprise-replicator/Dockerfile
debian/kafka-connect-base/Dockerfile
debian/server-connect-base/Dockerfile
debian/server-connect-base/include/etc/confluent/docker/apply-mesos-overrides
debian/server-connect-base/include/etc/confluent/docker/configure
debian/server-connect-base/include/etc/confluent/docker/ensure
debian/server-connect-base/include/etc/confluent/docker/kafka-connect.properties.template
debian/server-connect-base/include/etc/confluent/docker/launch
debian/server-connect-base/include/etc/confluent/docker/log4j.properties.template
debian/server-connect-base/include/etc/confluent/docker/run
debian/server-connect/Dockerfile

[CC-5454](https://confluentinc.atlassian.net/browse/CC-5454) covers how we plan to add two new enterprise Connect images that derive from `cp-server` instead of `cp-kafka`, and revert the recent changes for CC-5432 which added the `confluent-security` package to the `cp-kafka-connect-base` image.
[CC-5456](https://confluentinc.atlassian.net/browse/CC-5456) covers how we should alter our Replicator images to derive from `cp-server` instead of `cp-kafka` as well.
The changes here address both issues. Two new images, `cp-server-connect-base`, and `cp-server-connect`, are added; they mirror the existing `cp-kafka-connect-base` and `cp-kafka-connect` images and the only difference is that `cp-server-connect-base` inherits from `cp-server` instead of `cp-kafka`, `cp-server-connect` inherits …

CC-5454, CC-5456: Add new cp-server-connect-base and cp-server-connect images

---

debian/kafka-connect-base/include/etc/confluent/docker/log4j.properties.template

Apache Kafka 2.3 added support for MDC in logs. For reasons of backward compatibility, it is disabled in log output by default. 
This PR adds a new env variable to the Kafka Connect base image so that users can enable the MDC output in logs. 
`CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN` added as an optional environment variable. If present, the value provided is used in `log4j.appender.stdout.layout.ConversionPattern` of `connect-log4j.properties`
Log config `connect-log4j.properties` generated exactly as before
```
$ docker-compose up -d kafka-connect-01; sleep 30; docker exec kafka-connect-01 cat /etc/kafka/connect-log4j.properties
zookeeper is up-to-date
kafka is up-to-date
schema-registry is up-to-date
Recreating kafka-connect-01 ... done
log4j.rootLogger=INFO, stdout …
```

Add support for MDC output in logs

---

docs/development.rst
docs/operations/external-volumes.rst
docs/operations/logging.rst
docs/quickstart.rst
docs/tutorials/automatic-data-balancing.rst
docs/tutorials/clustered-deployment-sasl.rst
docs/tutorials/clustered-deployment-ssl.rst
docs/tutorials/clustered-deployment.rst
docs/tutorials/connect-avro-jdbc.rst
docs/tutorials/replicator.rst
docs/tutorials/tutorials.rst

https://confluentinc.atlassian.net/browse/DOCS-2187
- Fixed link to "extending Docker images" which is broken on [v.3.1.0](https://docs.confluent.io/3.1.0/cp-docker-images/docs/operations/logging.html#), 3.1.1, 3.1.2, 3.2.0, and 3.0.1 docs (won't fix 3.0.1, will fix others via `pint merge`)
- Fixed link to "tutorials section" which is broken on [v.3.1.0](https://docs.confluent.io/3.1.0/cp-docker-images/docs/quickstart.html), 3.1.1,  3.1.2, 3.2.0, and 3.0.1 docs (won't fix 3.0.1, will fix others via `pint merge`)
Signed-off-by: Victoria Bialas <vicky@confluent.io>

DOCS-2187 Fixed links CP Docker Images docs-customer feedback

---

debian/kafka-connect-base/Dockerfile
debian/kafka-connect-base/include/etc/confluent/docker/healthcheck.sh

This adds support for the Healthcheck functionality in Docker to Kafka Connect, enabling more accurate orchestration and management of containers. 
It works with both HTTP and HTTPS. 
There is a five-second polling interval, which is therefore the maximum that this would add to any dependents in starting. 
(supersedes https://github.com/confluentinc/cp-docker-images/pull/742)
Using [zero-to-hero](https://github.com/confluentinc/demo-scene/tree/master/kafka-connect-zero-to-hero), mounted the healthcheck script as an external file, and added `healthcheck` to the Docker Compose: 
healthcheck:
timeout: 10s
interval: 5s
retries: 120
test: /etc/confluent/docker/healthcheck.sh
volumes:
- /Users/Robin/git/cp-docker-images/debian/kafka-connect-base/include/etc/confluent/docker/healthcheck.sh:/etc/c …

Add healthcheck for Kafka Connect

---

debian/server/Dockerfile

With Schema Validator, we now need the security-plugins installed on the broker image itself.  This will install confluent-security into the cp-server image.
Signed-off-by: sdanduConf <sdandu@confluent.io>

add security plugins for schema validator to cp-server

---

debian/kafka-connect-base/include/etc/confluent/docker/configure
docs/config-reference.rst
docs/operations/external-volumes.rst

Fix #797. Now pass in an empty default so that if the variable isn't defined (which it doesn't have to be any more) the script doesn't fail.

Fix for issue 797

---

debian/base/include/etc/confluent/docker/bash-config

We don't want to log any sensitive data on startup, so I would like to exclude all of the BASIC_AUTH_USER_INFO fields from the `show_env` function. This will make sure that no sensitive data gets logged and sent to any shared logging systems.

Remove *BASIC_AUTH_USER_INFO fields from show_env

---

docs/config-reference.rst

This is used for building images for version 4.1.x or lower, and should not be used for adding new images.
For the 5.4.0 release and greater the images have been migrated to the following repositories:
* [common-docker](https://github.com/confluentinc/common-docker)
* [control-center-images](https://github.com/confluentinc/control-center-images)
* [kafkacat-images](https://github.com/confluentinc/kafkacat-images)
* [kafka-images](https://github.com/confluentinc/kafka-images)
* [kafka-mqtt-images](https://github.com/confluentinc/kafka-mqtt-images)
* [kafka-replicator-images](https://github.com/confluentinc/kafka-replicator-images)
* [kafka-rest-images](https://github.com/confluentinc/kafka-rest-images)
* [kafka-streams-examples](https://github.com/confluentinc/kafka-streams-examples)
* …

DOCS-6306: Remove proactive-support references

---

debian/base/Dockerfile
debian/base/Dockerfile.rpm

Theres no effective way to test this in CI/CD, so I'll just do it by hand in a `debian:jessie` container:
Check for regression
```
root@5bf63de6a936:/# curl -fSL "https://bootstrap.pypa.io/get-pip.py" | python
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 1883k  100 1883k    0     0  2152k      0 --:--:-- --:--:-- --:--:-- 2152k
Traceback (most recent call last):
File "<stdin>", line 24226, in <module>
File "<stdin>", line 199, in main
File "<stdin>", line 82, in bootstrap
File "/tmp/tmpl8JEuQ/pip.zip/pip/_internal/cli/main.py", line 60
sys.stderr.write(f"ERROR: {exc}")
^
SyntaxError: invalid syntax
```
Check the fix:
```
root@5bf63de6a936:/# curl -fSL "https://bootstrap.pypa.io/2.7/get-pip.py" | python
% …
```

fix: Pin bootstrap.pypa to a Python2.7 Script

---

debian/base/Dockerfile

confluent-docker-utils tag `v0.0.40-python2` update evicts some needless dependencies for runtime, and updates a couple of python modules to their latest python2 supported version.
This is used for building images for version 4.1.x or lower, and should not be used for adding new images.
For the 5.4.0 release and greater the images have been migrated to the following repositories:
* [common-docker](https://github.com/confluentinc/common-docker)
* [control-center-images](https://github.com/confluentinc/control-center-images)
* [kafkacat-images](https://github.com/confluentinc/kafkacat-images)
* [kafka-images](https://github.com/confluentinc/kafka-images)
* [kafka-mqtt-images](https://github.com/confluentinc/kafka-mqtt-images)
* [kafka-replicator-images](https://github.com/confluentinc/kafka- …

MINOR: Update version of docker-utils to v0.0.40-python2 and pip to latest py27 supported version

---

debian/base/Dockerfile

- Uses updated method of installing Zulu repos
- Installs only a headless JVM.
- Pins to version 8.0.302

MINOR: Pin Zulu OpenJDK JRE/JDK Headless to 8.0.302

---

debian/base/Dockerfile

It seems this cert has expired, and is getting in the way of importing GPG Keys:
```
root@4c33dd1858d0:/# openssl x509 -in /usr/share/ca-certificates/mozilla/DST_Root_CA_X3.crt -noout -text
Certificate:
Data:
Version: 3 (0x2)
Serial Number:
44:af:b0:80:d6:a3:27:ba:89:30:39:86:2e:f8:40:6b
Signature Algorithm: sha1WithRSAEncryption
Issuer: O=Digital Signature Trust Co., CN=DST Root CA X3
Validity
Not Before: Sep 30 21:12:19 2000 GMT
Not After : Sep 30 14:01:15 2021 GMT
```
This is a similar fix done in https://github.com/confluentinc/confluent-docker-build-images/pull/164

[skip secret scan] build: Remove expired ca-cert
